Sure, I'll guide you through the steps to push your project to GitHub and deploy it on Streamlit Cloud.

### Step 1: Initialize a Git Repository and Push to GitHub

1. **Initialize a Git repository:**
   Open a terminal and navigate to your project directory. Then run:
   ```sh
   git init
   ```

2. **Add your files to the repository:**
   ```sh
   git add .
   ```

3. **Commit your changes:**
   ```sh
   git commit -m "Initial commit"
   ```

4. **Create a new repository on GitHub:**
   Go to GitHub and create a new repository. Do not initialize it with a README, .gitignore, or license.

5. **Add the remote repository:**
   Replace `<your-github-username>` and `<your-repo-name>` with your GitHub username and the name of the repository you created.
   ```sh
   git remote add origin https://github.com/<your-github-username>/<your-repo-name>.git
   ```

6. **Push your changes to GitHub:**
   ```sh
   git push -u origin master
   ```

### Step 2: Deploy to Streamlit Cloud

1. **Go to Streamlit Cloud:**
   Visit [Streamlit Cloud](https://share.streamlit.io/) and sign in with your GitHub account.

2. **Create a new app:**
   - Click on "New app".
   - Select the repository you just pushed.
   - Choose the branch (usually `master` or `main`).
   - Enter the path to your Streamlit app file (`app.py`).

3. **Deploy the app:**
   Click on "Deploy". Streamlit Cloud will automatically install the dependencies listed in `requirements.txt` and deploy your app.

### Example `.streamlit/config.toml` (Optional)

You can create a `.streamlit/config.toml` file to customize the Streamlit app settings.

[server]
headless = true
port = $PORT
enableCORS = false
